Feat/repeatable program stage
EyeSeeTea/amr-surveys pull request #25
Opened 2024-03-20 15:55 UTC by 9sneha-n

### :pushpin: References

-   **Issue:** Closes #?

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

### :fire: Notes to the tester

2024-04-01 08:49 UTC, anagperal commented on src/domain/usecases/GetSurveyUseCase.ts
> +        } else if (parentPrevalenceSurveyId) {
Nice :)

2024-04-01 08:49 UTC, anagperal commented on src/domain/usecases/GetSurveyUseCase.ts
> +            return this.getPPSSurveyForm(programId, parentPPSSurveyId, parentWardRegisterId);
Nice!

2024-04-01 08:57 UTC, anagperal commented on src/webapp/components/survey/SurveyForm.tsx
> +    const updateQuestion = (question: Question, stageId?: string) => {
This kind of functions: saveSurveyForm, updateQuestion, addProgramStage, removeProgramStage are logic and I think they should be placed in a hook

2024-04-01 09:01 UTC, anagperal requested changes
Thanks @9sneha-n !! I have added some comments but they do not affect the functionality of the task, if code needs to be changed it can be done later if there is no time

2024-04-01 18:35 UTC, 9sneha-n commented
> Thanks @9sneha-n !! I have added some comments but they do not affect the functionality of the task, if code needs to be changed it can be done later if there is no time

Thanks @anagperal  for the review, addressed the review comments.

2024-04-02 06:39 UTC, anagperal requested changes
thanks @9sneha-n ! Just one last change, add `useCallback` to the functions of the hook to improve performance

2024-04-03 11:57 UTC, 9sneha-n commented
> thanks @9sneha-n ! Just one last change, add `useCallback` to the functions of the hook to improve performance

Thank you, @anagperal, i missed that  . Have now added usecallbacks

2024-04-03 13:57 UTC, anagperal approved these changes
thanks @9sneha-n !

2024-04-04 06:25 UTC, 9sneha-n commented
> thanks @9sneha-n !

Thanks @anagperal

2024-04-08 09:27 UTC, merged