Prevalence - Add children number to columns in Surveys
EyeSeeTea/amr-surveys pull request #31
Opened 2024-04-17 17:03 UTC by davidbgomes

### :pushpin: References

-   **Issue:** Closes #8693c8r5v [display number of children in lists](https://app.clickup.com/t/8693c8r5v)

### :memo: Implementation

- Add children count when mapping the Surveys, splitted the logic of mapping with and without children (only for non-paginated surveys), since it can be an intensive task. Right now only for the first two Prevalence surveys, like in the description.

### :video_camera: Screenshots/Screen capture
<img width="1489" alt="image" src="https://github.com/EyeSeeTea/amr-surveys/assets/44171664/4fedccf2-d100-4058-978e-79d9e6c97a26">
<img width="1234" alt="image" src="https://github.com/EyeSeeTea/amr-surveys/assets/44171664/51ff4b74-a7ac-43c5-83f9-17d364be56b6">

### :fire: Notes to the tester

2024-04-22 05:52 UTC, 9sneha-n requested changes
@davidbgomes these changes are not required. There is a function called GetChildCountUseCase.execute() which will return you the child count, you can move the logic of the function into a util function and call it(as a user case should not call a use case) from GetAllSurveysUseCase and GetPaginatedPatientSurveysUseCase.

2024-04-22 16:59 UTC, davidbgomes commented
Thanks @9sneha-n , that is cleaner approach. I've reverted the changes and done it that way.

2024-04-25 05:32 UTC, 9sneha-n reviewed
Couple of small changes requested, not a blocker, can be addressed in next PR.

2024-04-25 05:32 UTC, 9sneha-n commented on src/webapp/components/survey-list/table/SurveyListTable.tsx
> +const getChildrenName = (surveyFormType: SURVEY_FORM_TYPES): string => {
move function to domain utils file as this is biz logic.

2024-04-25 05:32 UTC, 9sneha-n commented on src/webapp/components/survey-list/table/SurveyListTable.tsx
> +                                    {[
create and export array in domain like SURVEYS_WITH_CHILD_COUNT or with appropriate name and use it everywhere.

2024-04-25 05:34 UTC, 9sneha-n commented
@MiquelAdell With the new approach , it is possible to show child count for all survey types with no extra effort. Please let us know if that change is required.

2024-04-25 12:06 UTC, MiquelAdell commented
@davidbgomes go ahead and display children count in all lists with children. 
For example, a Prevalence survey has countries, so the column will be "countries (3)".
The only case for which we have multiple children is patient in prevalence in that case I would display all columns with the numbers

![Screenshot 2024-04-25 at 14 05 51](https://github.com/EyeSeeTea/amr-surveys/assets/4996457/4b3a0fc4-5d7b-4db5-a29e-873237aeeda6)

Also if you could merge development into this PR to solve the conflict.

Thanks!

2024-05-02 12:12 UTC, MiquelAdell approved these changes

2024-05-02 14:20 UTC, davidbgomes commented
@MiquelAdell @9sneha-n I've made the changes requested, and also worked on having the paginated surveys, and PPS surveys also show the childCount.

2024-05-07 04:24 UTC, 9sneha-n requested changes
Thanks @davidbgomes Overall loos great, some changes requested.

2024-05-07 04:24 UTC, 9sneha-n commented on src/domain/utils/getChildCount.ts
> +import { FutureData } from "../../data/api-futures";
rename file to getChildCountHelper

2024-05-07 04:24 UTC, 9sneha-n commented on src/webapp/components/survey-list/hook/useDeleteSurvey.ts
> +            typeof survey.childCount === "number"
please use childCount.type instead of typeof childCount

2024-05-07 04:24 UTC, 9sneha-n commented on src/webapp/components/survey-list/hook/useSurveyListActions.ts
> +        if (typeof childCount === "number") {
please use childCount.type instead of typeof childCount

2024-05-07 04:24 UTC, 9sneha-n commented on src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
> +    const [sampleShipmentsSortDirection, setSampleShipmentsSortDirection] =
move all the child column sorting states, logic and onclick handler to a customHook called useMultipleChilCount or something similar

2024-05-07 04:24 UTC, 9sneha-n commented on src/webapp/components/survey-list/table/PaginatedSurveyListTable.tsx
> +                                                    typeof survey.childCount !== "number" &&
use childCount.type instead of typeof

2024-05-09 12:51 UTC, 9sneha-n approved these changes
[code-only review] Thanks @davidbgomes 
Tracking refactor in https://app.clickup.com/t/8694h685h

2024-05-14 11:29 UTC, merged