Populate Survey id
EyeSeeTea/amr-surveys pull request #44
Opened 2024-05-14 17:59 UTC by davidbgomes

### :pushpin: References

-   **Issue:** Closes #8694fg8tv [survey id not shown in survey form (at least in prevalence)](https://app.clickup.com/t/8694fg8tv)

### :memo: Implementation

- Add eventId or trackedEntityId to surveyId question.

### :video_camera: Screenshots/Screen capture
<img width="997" alt="image" src="https://github.com/EyeSeeTea/amr-surveys/assets/44171664/85ecb407-6156-48a5-9e49-20430848f920">

### :fire: Notes to the tester

2024-05-14 17:59 UTC, ifoche commented
Task linked: [CU-8694fg8tv survey id not shown in survey form (at least in prevalence)](https://app.clickup.com/t/8694fg8tv)

2024-05-15 18:18 UTC, 9sneha-n requested changes
Please test this code change impact on other survey forms - Especially forms which have ward id and facility id., This will incorrectly set the ward id as well as the if condition matches other fields including ward fields as well.

2024-05-23 19:40 UTC, davidbgomes commented
thanks @9sneha-n , should be fixed now

2024-05-24 07:48 UTC, 9sneha-n requested changes
@davidbgomes this is setting the Survey Id of child surveys incorrectly. you need to add a surveyFormType === "PPSSurveyForm" || "PrevalenceSurveyForm".Also, for child surveys, the parent survey id should be set based on module. @MiquelAdell This change is quite drastic, all the parent child mappings will get jumbled. Let's test this PR extensively (after code update) before merge.

<img width="1728" alt="Screenshot 2024-05-24 at 1 11 22 PM" src="https://github.com/EyeSeeTea/amr-surveys/assets/83749675/3f67b2ab-84dc-4efe-90c2-8770d25a49a4">
<img width="1728" alt="Screenshot 2024-05-24 at 1 12 11 PM" src="https://github.com/EyeSeeTea/amr-surveys/assets/83749675/ec8068eb-06ba-4eaf-a26e-8a41ddc65825">

2024-08-14 03:42 UTC, closed without merging