feat: antibiotics treatment episode as table
EyeSeeTea/amr-surveys pull request #64
Opened 2024-07-26 06:09 UTC by 9sneha-n

### :pushpin: References

-   **Issue:** Closes #? https://app.clickup.com/t/86953e1c3, #86953e1c3

### :memo: Implementation
1. Identify Antibiotics Treatment Hospital Episode Section
2. Parse the header row from the questions by grouping 
3. Identify column questions and details questions - all questions are in column except "Please specify Other" on other select
4. Display column questions in column, and Please specify Other as row. 
5. Fix edit bug in Prevalence Mortality forms

### :video_camera: Screenshots/Screen capture

Uploading AntibioticTreatmentsTable.mov…

### :fire: Notes to the tester

2024-07-26 06:09 UTC, ifoche commented
Task linked: [CU-86953e1c3 Display antibiotics in "Antibiotic treatments during hospital episode" in discharge from as a table](https://app.clickup.com/t/86953e1c3)

2024-08-02 07:12 UTC, MiquelAdell approved these changes
all ok by me

2024-08-08 10:07 UTC, anagperal commented on src/webapp/components/survey/TableSection.tsx
> +                                            <DataTableCell key={question.code}>
(code-only review) This part of the code is very similar to the code below, and also to the code in SurveySection.tsx. If you have time, maybe would be interesting to merge and create just one component to be use in TableSection and in SurveySection components

2024-08-08 10:09 UTC, anagperal requested changes
thanks @9sneha-n ! All good, I have added one minor comment that if there is no time it's not needed to be done (code-only review)

2024-08-14 09:13 UTC, ifoche approved these changes
thanks @9sneha-n

2024-08-14 09:14 UTC, ifoche commented
Just a quick note, we are merging it as the procedure for generating staging versions is unclear and we have to create a new release

2024-08-14 09:14 UTC, merged