feat: implement data element validation and add codec utilities
EyeSeeTea/amr-surveys pull request #76
Opened 2024-12-18 22:19 UTC by MatiasArriola

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/86970by09  #86970by09

### :memo: Implementation

- The application expected the `dataElement.formName` property to always be a `string`. When the API returned `undefined` in certain scenarios, this caused errors downstream - such as the `Cannot read properties of undefined (reading 'includes')` error from the bug report.
- The idea behind this PR is to validate the response contents early, so invalid objects are caught and reported instead of propagated.
- I took the [know-how wiki](https://github.com/EyeSeeTea/know-how/wiki/Typescript) and other EST projects as reference, so I added the Codec utilities.
- Copied the `codec.ts` utilities from [metadata-sync](https://github.com/EyeSeeTea/metadata-synchronization-blessed/blob/61c9010b78b82d4ac6e8dcd4ca0e0f5374e99248/src/utils/codec.ts#L4).
- Not only `formName` will be validated, but also other props from the `ProgramDataElement` type, so we make sure the real object will match its typing.
- This validation is specific to the Surveys Form dataElements, but a similar approach could be extended to other parts of the app and entities, in order to catch possible metadata configuration issues or data inconsistencies early.

### :video_camera: Screenshots/Screen capture

Errors forced during testing, since the original error is now corrected in the test environment,

![Screenshot from 2024-12-18 15-08-18](https://github.com/user-attachments/assets/134fe9d5-9145-41b5-9c56-697cafce93ce)
![Screenshot from 2024-12-18 15-08-51](https://github.com/user-attachments/assets/56329fbe-378c-40c0-9c01-fd9b725c73c4)

### :fire: Notes to the tester

- A simplified error will be shown in the snackbar, and more details are logged to the console to make troubleshooting easier.

2024-12-18 22:19 UTC, ifoche commented
Task linked: [CU-86970by09 Fix "Cannot read properties of undefined (reading 'includes')" due to changes to the PPS program](https://app.clickup.com/t/86970by09)

2024-12-19 13:57 UTC, anagperal requested changes
thanks @MatiasArriola this works great!
I don't know too much about Codec in metadata sync, I have used it in glass-admin to validate data to be stored in the datastore and also when we get that data from there in another app (as we can store there the data in any form). But with data comming from metadata endpoint in d2-api I think it may be enough to type the result well. I think you can keep Codec, but also change in interface `ProgramDataElement` the property to `formName?` as can be undefined too

2024-12-20 15:54 UTC, MatiasArriola commented
I’ve implemented the requested changes, and the code is now simpler.
An error is now thrown if either `formName` or `code` is missing from the `ProgramDataElement` or the `TrackedEntityAttibute`. Also, I improved the error message to be more descriptive:

![Screenshot from 2024-12-20 12-45-01](https://github.com/user-attachments/assets/92c01a44-e39a-4484-ad2c-e1a72a9aaf1c)

Please let me know your thoughts!

2024-12-23 07:38 UTC, anagperal approved these changes
thanks @MatiasArriola !!

2025-01-02 07:22 UTC, merged